# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f93ccff5f8d46642a764f45c22adb32c729f0a5224ed768d1ae732c83a8050e6acdcf95d50be7d5d64dc86ec3d755a5c6c6ffe155c271a4283131c73082696b

test:
  secret_key_base: 50bf8d2926ea9abcb87932d57c17ab93fd5b97f4eda19a9819eebf5ace990bb8686b5f3ebbdedd85f512803ac59b8713d8eaac01f539883af386f53b62a2af67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
